# Generated by Django 4.2 on 2023-05-12 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.FileField(upload_to='media/profile_pic')),
                ('possession', models.FileField(upload_to='media/profile_pic')),
                ('landtax', models.FileField(upload_to='media/profile_pic')),
                ('progress', models.CharField(max_length=80)),
                ('status', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='users',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.DeleteModel(
            name='Contractor',
        ),
        migrations.AddField(
            model_name='application',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.users'),
        ),
    ]
