# Generated by Django 4.2 on 2023-05-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_contractor_application_contractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
