# Generated by Django 4.2 on 2023-05-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_contractor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='aadhar',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='progress',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
