# Generated by Django 4.2 on 2023-05-13 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_aadhar_application_aadhaar'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.plan'),
        ),
    ]
